# This backtester uses signals generated by the strategy module.
# It reads buy and sell signals from the strategy, enters a position on the
# next day after a buy signal, and exits a position based on predefined rules:
# a stop loss, a sell signal, or reaching the final bar of the dataset. While
# running, it tracks whether a position is open, calculates the strategy’s
# daily returns only when in a trade, and compounds those returns over time
# to produce a cumulative performance curve. It also records individual trades
# and provides summary statistics at the end to evaluate the overall performance
# of the strategy, and make the numbers easier to understand.


from signal import signal

import pandas as pd


class Backtester:
    def __init__(
        self, strategy, initial_capital: float = 10000, percent_per_trade: float = 1.0
    ):
        self.strategy = strategy
        self.data = strategy.data.copy()
        self.capital = initial_capital
        self.initial_capital = initial_capital
        self.percent_per_trade = percent_per_trade
        self.trades = []

    def exit_positions(self, current_price, reason):
        for trade in self.trades:
            if trade["exit_price"] is None:  # only exit open trades
                trade["exit_price"] = current_price
                trade["return"] = (trade["exit_price"] - trade["entry_price"]) / trade[
                    "entry_price"
                ]
                trade["reason"] = reason
                self.portfoloio_value += trade["exit_price"] * trade["num_shares"]

    def check_stop_loss(self, current_price):
        for trade in self.trades:
            if (
                trade["stop_loss"] is not None
                and current_price <= trade["stop_loss"]
                and trade["exit_price"] is None
            ):
                trade["exit_price"] = current_price
                trade["return"] = (trade["exit_price"] - trade["entry_price"]) / trade[
                    "entry_price"
                ]
                trade["reason"] = "stop_loss"
                self.portfoloio_value += trade["exit_price"] * trade["num_shares"]

    def backtest(self, stop_loss_pct: float = 0.10):
        # then when running the code we can set our own stop loss
        # by overriding the default value of 10%
        required_cols = {"Open", "Close", "Return", "signal"}

        missing = required_cols - set(self.data.columns)
        if missing:
            raise ValueError(f"Missing required columns: {missing}")

        self.data["position"] = 0
        self.data["strategy_return"] = 0.0

        position = 0
        entry_price = None
        entry_date = None
        today_close = None

        for i in range(1, len(self.data)):
            today_close = self.data["Close"].iloc[i]
            today_open = self.data["Open"].iloc[i]
            previous_signal = self.data["signal"].iloc[i - 1]

            if previous_signal == 1 & self.capital > 0:
                position = 1
                entry_price = today_open
                entry_date = self.data.index[i]
                amount_to_invest = self.capital * self.percent_per_trade
                num_shares = amount_to_invest // entry_price
                self.capital -= num_shares * entry_price
                self.trades.append(
                    {
                        "entry_date": entry_date,
                        "entry_price": entry_price,
                        "exit_date": None,
                        "exit_price": None,
                        "return": None,
                        "reason": None,
                        "num_shares": num_shares,
                        "stop_loss": entry_price * (1 - stop_loss_pct),
                        "capital_invested": num_shares * entry_price,
                    }
                )

            elif previous_signal == -1 and position == 1:
                self.exit_positions(today_close, reason="signal_exit")
                position = 0

            self.check_stop_loss(today_close)

        # exit any remaining open positions at the end of the backtest
        self.exit_positions(today_close, reason="end_of_backtest")

        self.data["strategy_return"] = self.capital / self.initial_capital - 1

        return self.data

    def stats(self):

        returns = pd.Series(
            [t["return"] for t in self.trades if t["return"] is not None]
        )

        return {
            "num_trades": len(self.trades),
            "win_rate": (returns > 0).mean(),
            "avg_trade_return": returns.mean(),
            "best_trade": returns.max(),
            "worst_trade": returns.min(),
            "total_strategy_return": self.data["strategy_return"].iloc[-1],
        }
