# This backtester uses signals generated by the strategy module.
# It reads buy and sell signals from the strategy, enters a position on the
# next day after a buy signal, and exits a position based on predefined rules:
# a stop loss, a sell signal, or reaching the final bar of the dataset. While
# running, it tracks whether a position is open, calculates the strategy’s
# daily returns only when in a trade, and compounds those returns over time
# to produce a cumulative performance curve. It also records individual trades
# and provides summary statistics at the end to evaluate the overall performance
# of the strategy, and make the numbers easier to understand.


import pandas as pd


class Backtester:
    def __init__(
        self, strategy, initial_capital: float = 10000, percent_per_trade: float = 1.0
    ):
        self.strategy = strategy
        self.data = strategy.data.copy()
        self.initial_capital = initial_capital
        self.percent_per_trade = percent_per_trade
        self.trades = []

    def backtest(self, stop_loss_pct: float = 0.10):
        # then when running the code we can set our own stop loss
        # by overriding the default value of 10%
        required_cols = {"Open", "Close", "Return", "signal"}

        missing = required_cols - set(self.data.columns)
        if missing:
            raise ValueError(f"Missing required columns: {missing}")

        self.data["position"] = 0
        self.data["strategy_return"] = 0.0

        position = 0
        entry_price = None
        entry_date = None

        for i in range(1, len(self.data)):
            today_close = self.data["Close"].iloc[i]
            today_open = self.data["Open"].iloc[i]
            previous_signal = self.data["signal"].iloc[i - 1]

            if position == 0:
                if previous_signal == 1:
                    position = 1
                    entry_price = today_open
                    entry_date = self.data.index[i]

                    self.trades.append(
                        {
                            "entry_date": entry_date,
                            "entry_price": entry_price,
                            "exit_date": None,
                            "exit_price": None,
                            "return": None,
                            "reason": None,
                        }
                    )

            else:
                stop_price = entry_price * (1 - stop_loss_pct)
                exit_reason = None
                exit_price = None

                if today_close <= stop_price:
                    exit_reason = "stop_loss"
                    exit_price = today_close
                elif previous_signal == -1:
                    exit_reason = "signal_exit"
                    exit_price = today_close
                elif i == len(self.data) - 1:
                    exit_reason = "final_bar"
                    exit_price = today_close

                if exit_reason is not None:
                    trade_return = (exit_price - entry_price) / entry_price

                    self.trades[-1]["exit_date"] = self.data.index[i]
                    self.trades[-1]["exit_price"] = exit_price
                    self.trades[-1]["return"] = trade_return
                    self.trades[-1]["reason"] = exit_reason

                    position = 0
                    entry_price = None
                    entry_date = None

            self.data.loc[self.data.index[i], "position"] = position

        self.data["strategy_return"] = self.data["Return"] * self.data[
            "position"
        ].shift(1).fillna(0)
        self.data["cumulative_strategy_return"] = (
            1 + self.data["strategy_return"]
        ).cumprod() - 1
        self.data["cumulative_buy_and_hold_return"] = (
            1 + self.data["Return"]
        ).cumprod() - 1

        return self.data

    def stats(self):
        closed_trades = [t for t in self.trades if t["return"] is not None]
        if not closed_trades:
            return {}

        returns = pd.Series([t["return"] for t in closed_trades])

        return {
            "num_trades": len(closed_trades),
            "win_rate": (returns > 0).mean(),
            "avg_trade_return": returns.mean(),
            "best_trade": returns.max(),
            "worst_trade": returns.min(),
            "total_strategy_return": self.data["cumulative_strategy_return"].iloc[-1],
            "buy_and_hold_return": self.data["cumulative_buy_and_hold_return"].iloc[-1],
        }
